name: Test action
on: [push]
jobs:
    say_hello:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 
              uses: actions/checkout@v4
            - name: Print
              run: echo "Hello, world"
   