name: Interact with ChatGPT
on: 
  issues:
    types: [opened, reopened, labeled]
jobs:
    access_issue_info:
        runs-on: ubuntu-latest
        if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
        steps:
            - name: Checkout 
              uses: actions/checkout@v4
            - name: Make script executable
              run: chmod +x ./scripts/script.sh
            - name: Generate Code with ChatGPT
              id: generate_code
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                REPOSITORY: $GITHUB_REPOSITORY
                ISSUE_NUMBER: ${{ github.event.issue.number }}
                OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                
              run: ./scripts/script.sh $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY
            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                name: autocoder-artifact
                path: autocoder-bot
                if-no-files-found: error
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: autocoder-artifact
            - name: Display Generated Code using the ls command
              run: ls -R autocoder-artifact
 
    
   
