name: Interact with ChatGPT
on: 
  issues:
    types: [opened, reopened]
jobs:
    access_issue_info:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 
              uses: actions/checkout@v4
            - name: Generate Code with ChatGPT
              id: generate_code
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                REPOSITORY: $GITHUB_REPOSITORY
                ISSUE_NUMBER: ${{ github.event.issue.number }}
                OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
              run: ./scripts/script.sh ${{ GITHUB_TOKEN }} ${{ REPOSITORY }} ${{ ISSUE_NUMBER }} ${{ OPENAI_API_KEY }}
   
